name: WorldGuardless
author: https://lode.gg/
description: WorldGuardless is a plugin that allows you to disable all those annoying default WorldGuard commands.
version: '1.0.0'
main: gg.lode.worldguardless.WorldGuardless
api-version: '1.20'
depend:
  - WorldGuard
loadbefore:
  - WorldGuard